/**
 * euroGovernance - Declarative Onboarding Persona Step Definitions
 */

import { UserRole, OnboardingStepDefinition } from '@eurogovernance/shared-types';

export interface PersonaFlowConfig {
  role: UserRole;
  badge: string;
  title: string;
  subtitle: string;
  defaultTab: string;
  steps: OnboardingStepDefinition[];
}

export const PERSONA_ONBOARDING_FLOWS: Record<string, PersonaFlowConfig> = {
  tenant_admin: {
    role: 'tenant_admin',
    badge: 'GENESIS SETUP',
    title: 'Initialize Sovereign Compliance Baseline',
    subtitle: 'Configure legal entity boundaries, select applicable EU regulations, and appoint domain leads.',
    defaultTab: 'overview',
    steps: [
      {
        id: 'admin_org_profile',
        stepIndex: 0,
        title: 'Organization Baseline',
        subtitle: 'Define legal entity boundaries and statutory European data residency.',
        icon: '🏢',
        targetTab: 'overview',
        isMutating: true,
        complianceImpact: 'Establishes statutory Lead Supervisory Authority jurisdiction (GDPR Art. 56).',
        recommendedActionLabel: 'Configure Legal Entity',
      },
      {
        id: 'admin_framework_scope',
        stepIndex: 1,
        title: 'Regulatory Framework Scope',
        subtitle: 'Select applicable European directives and certifiable security standards.',
        icon: '📐',
        targetTab: 'frameworks',
        isMutating: true,
        complianceImpact: 'Initializes domain-specific requirement mappings and control libraries.',
        recommendedActionLabel: 'Select Frameworks',
      },
      {
        id: 'admin_scoping_rules',
        stepIndex: 2,
        title: 'Fast-Track Scoping & Harmonization',
        subtitle: 'Answer 4 operational questions to automatically filter non-applicable controls.',
        icon: '⚖️',
        targetTab: 'applicability_review',
        isMutating: true,
        complianceImpact: 'Condenses raw requirements into a unified, non-duplicative control inventory.',
        recommendedActionLabel: 'Run Scoping Engine',
      },
      {
        id: 'admin_appoint_leads',
        stepIndex: 3,
        title: 'Appoint Governance Leads',
        subtitle: 'Delegate specialized statutory domains to internal compliance and security officers.',
        icon: '👥',
        targetTab: 'members',
        isMutating: true,
        complianceImpact: 'Distributes operational workflows across DPO, CISO, and AI leads upon first login.',
        recommendedActionLabel: 'Invite Team Leads',
      },
      {
        id: 'admin_governance_policies',
        stepIndex: 4,
        title: 'Evidence Governance & Policies',
        subtitle: 'Enforce sovereign audit rules before operational evidence ingestion begins.',
        icon: '🛡️',
        targetTab: 'controls',
        isMutating: true,
        complianceImpact: 'Locks in Four-Eyes authorization and cryptographic SHA-256 verification.',
        recommendedActionLabel: 'Enforce Security Policies',
      },
    ],
  },

  compliance_manager: {
    role: 'compliance_manager',
    badge: 'GOVERNANCE ONBOARDING',
    title: 'Multi-Framework Scoping & Harmonization',
    subtitle: 'Answer scoping questions to filter non-applicable controls and generate your Statement of Applicability (SoA).',
    defaultTab: 'coverage_dashboard',
    steps: [
      {
        id: 'comp_scoping',
        stepIndex: 0,
        title: 'Operational Scoping Questionnaire',
        subtitle: 'Fine-tune 8 operational parameters to finalize applicable requirements across GDPR & ISO.',
        icon: '📐',
        targetTab: 'applicability_review',
        isMutating: true,
        complianceImpact: 'Determines requirement applicability for the formal Statement of Applicability (SoA).',
        recommendedActionLabel: 'Complete Scoping Questions',
      },
      {
        id: 'comp_exclusions',
        stepIndex: 1,
        title: 'Applicability Determinations',
        subtitle: 'Provide formal statutory justifications for excluded ISO 27001 Annex A controls.',
        icon: '⚖️',
        targetTab: 'applicability_review',
        isMutating: true,
        complianceImpact: 'Mandatory for ISO 27001 certification audit readiness.',
        recommendedActionLabel: 'Document Exclusions',
      },
      {
        id: 'comp_controls_review',
        stepIndex: 2,
        title: 'Unified Controls Inventory Inspection',
        subtitle: 'Inspect mapped control overlaps and verify 100% requirement coverage.',
        icon: '🛡️',
        targetTab: 'controls',
        isMutating: false,
        complianceImpact: 'Ensures zero orphaned regulatory obligations exist.',
        recommendedActionLabel: 'Inspect Controls Catalog',
      },
      {
        id: 'comp_export_dossier',
        stepIndex: 3,
        title: 'Statement of Applicability Pre-flight Scan',
        subtitle: 'Run automated audit check and export baseline Statement of Applicability PDF.',
        icon: '📦',
        targetTab: 'exports',
        isMutating: true,
        complianceImpact: 'Generates non-repudiable baseline snapshot for external auditors.',
        recommendedActionLabel: 'Export SoA Dossier',
      },
    ],
  },

  privacy_manager: {
    role: 'privacy_manager',
    badge: 'STATUTORY PRIVACY',
    title: 'GDPR Article 30 & Transfer Governance',
    subtitle: 'Document processing activities, map cross-border data flows (TIAs), and verify Article 28 DPAs.',
    defaultTab: 'gdpr',
    steps: [
      {
        id: 'dpo_ropa',
        stepIndex: 0,
        title: 'Article 30 Processing Activities Setup',
        subtitle: 'Select pre-built ROPA templates for Customer CRM, HR Payroll, and Cloud Analytics.',
        icon: '🇪🇺',
        targetTab: 'gdpr',
        isMutating: true,
        complianceImpact: 'Satisfies mandatory GDPR Article 30 accountability obligations.',
        recommendedActionLabel: 'Initialize ROPA Entries',
      },
      {
        id: 'dpo_transfers',
        stepIndex: 1,
        title: 'Cross-Border Data Flow Mapping (TIAs)',
        subtitle: 'Identify non-EEA cloud processors and attach Standard Contractual Clauses (SCCs).',
        icon: '🌍',
        targetTab: 'processor_transfers',
        isMutating: true,
        complianceImpact: 'Ensures compliance with GDPR Chapter V and Schrems II transfer rules.',
        recommendedActionLabel: 'Map Cross-Border Transfers',
      },
      {
        id: 'dpo_dpa_audit',
        stepIndex: 2,
        title: 'Article 28 DPA Verification',
        subtitle: 'Verify executed Data Processing Agreements for all active suppliers.',
        icon: '📜',
        targetTab: 'processor_hub',
        isMutating: true,
        complianceImpact: 'Eliminates uncontracted subprocessor liability under GDPR Art. 28(3).',
        recommendedActionLabel: 'Audit DPA Contracts',
      },
    ],
  },

  ai_governance_manager: {
    role: 'ai_governance_manager',
    badge: 'EU AI ACT CONFORMITY',
    title: 'AI Model Register & Risk Classification',
    subtitle: 'Inventory organization AI systems, screen for Article 5 prohibitions, and compile technical dossiers.',
    defaultTab: 'ai_systems',
    steps: [
      {
        id: 'ai_register',
        stepIndex: 0,
        title: 'Register Foundation AI Models',
        subtitle: 'Capture model name, intended purpose, foundation model provider, and deployment context.',
        icon: '🤖',
        targetTab: 'ai_systems',
        isMutating: true,
        complianceImpact: 'Maintains statutory inventory under EU Regulation 2024/1689.',
        recommendedActionLabel: 'Register First AI Model',
      },
      {
        id: 'ai_screening',
        stepIndex: 1,
        title: 'Article 5 Prohibited Practice Screening',
        subtitle: 'Screen for subliminal manipulation, sensitive trait categorization, and social scoring.',
        icon: '🚫',
        targetTab: 'ai_systems',
        isMutating: true,
        complianceImpact: 'Ensures zero prohibited artificial intelligence practices exist.',
        recommendedActionLabel: 'Run Prohibited Screening',
      },
      {
        id: 'ai_annex_three',
        stepIndex: 2,
        title: 'Annex III High-Risk Classification',
        subtitle: 'Evaluate model impact on employment, critical systems, or credit scoring.',
        icon: '⚖️',
        targetTab: 'ai_systems',
        isMutating: true,
        complianceImpact: 'Determines mandatory technical file obligations and conformity requirements.',
        recommendedActionLabel: 'Determine Risk Tier',
      },
    ],
  },

  security_manager: {
    role: 'security_manager',
    badge: 'SECURITY & ASSURANCE',
    title: 'Third-Party Governance & Control Verification',
    subtitle: 'Import critical infrastructure suppliers, dispatch due diligence assessments, and upload ISO 27001 certs.',
    defaultTab: 'processor_hub',
    steps: [
      {
        id: 'sec_import_processors',
        stepIndex: 0,
        title: 'Core Processor Roster Setup',
        subtitle: 'Import critical hosting providers, cloud databases, and SaaS suppliers.',
        icon: '🏢',
        targetTab: 'processor_inventory',
        isMutating: true,
        complianceImpact: 'Establishes supplier inventory required by ISO 27001 A.5.19.',
        recommendedActionLabel: 'Import Critical Vendors',
      },
      {
        id: 'sec_dispatch_assessment',
        stepIndex: 1,
        title: 'Dispatch Due Diligence Assessment',
        subtitle: 'Generate zero-login tokenized Magic Link and dispatch security questionnaire.',
        icon: '📋',
        targetTab: 'processor_assessments',
        isMutating: true,
        complianceImpact: 'Validates vendor technical and organizational security measures (TOMs).',
        recommendedActionLabel: 'Dispatch Questionnaire',
      },
      {
        id: 'sec_cert_vault',
        stepIndex: 2,
        title: 'Upload Master Certifications',
        subtitle: 'Deposit ISO 27001 / SOC 2 certificates and configure surveillance audit alerts.',
        icon: '🏆',
        targetTab: 'certifications',
        isMutating: true,
        complianceImpact: 'Enables automated expiry alerts and continuous assurance tracking.',
        recommendedActionLabel: 'Deposit Certificate',
      },
    ],
  },

  auditor: {
    role: 'auditor',
    badge: 'AUDITOR WORKSPACE',
    title: 'Independent Assurance & Evidence Inspection',
    subtitle: 'Inspect scoped requirements, verify SHA-256 evidence integrity chains, and download export packages.',
    defaultTab: 'overview',
    steps: [
      {
        id: 'audit_soa_inspect',
        stepIndex: 0,
        title: 'Statement of Applicability Review',
        subtitle: 'Inspect mapped requirements and legal justifications for excluded controls.',
        icon: '📐',
        targetTab: 'coverage_dashboard',
        isMutating: false,
        complianceImpact: 'Validates formal certification boundaries and justification sufficiency.',
        recommendedActionLabel: 'Inspect Scoping Matrix',
      },
      {
        id: 'audit_evidence_sample',
        stepIndex: 1,
        title: 'Cryptographic Evidence Sampling',
        subtitle: 'Verify client-side SHA-256 hashes and Four-Eyes authorizer separation.',
        icon: '🔍',
        targetTab: 'evidence',
        isMutating: false,
        complianceImpact: 'Confirms non-repudiation and evidence authenticity.',
        recommendedActionLabel: 'Sample Evidence Locker',
      },
      {
        id: 'audit_export_archive',
        stepIndex: 2,
        title: 'Compile Complete Audit ZIP',
        subtitle: 'Trigger background compiler to generate timestamped evidence archive.',
        icon: '📦',
        targetTab: 'exports',
        isMutating: true,
        complianceImpact: 'Provides immutable offline dossier for statutory audit workpapers.',
        recommendedActionLabel: 'Generate Audit Package',
      },
    ],
  },

  contributor: {
    role: 'contributor',
    badge: 'ACTION REQUIRED',
    title: 'Assigned Remediation & Evidence Inbox',
    subtitle: 'Review controls assigned to your queue and upload evidence with automated cryptographic checksums.',
    defaultTab: 'evidence',
    steps: [
      {
        id: 'contrib_queue',
        stepIndex: 0,
        title: 'Review Assigned Controls Queue',
        subtitle: 'Inspect technical controls requiring implementation or evidence artifacts.',
        icon: '📋',
        targetTab: 'evidence',
        isMutating: false,
        complianceImpact: 'Aligns day-to-day engineering tasks with regulatory requirements.',
        recommendedActionLabel: 'View Assigned Controls',
      },
      {
        id: 'contrib_upload',
        stepIndex: 1,
        title: 'Upload Evidence with Cryptographic Hash',
        subtitle: 'Upload implementation screenshots or configuration logs with automated SHA-256 validation.',
        icon: '📤',
        targetTab: 'evidence',
        isMutating: true,
        complianceImpact: 'Furnishes proof of control enforcement for compliance audit.',
        recommendedActionLabel: 'Upload Evidence Artifact',
      },
    ],
  },
};
