/**
 * euroGovernance - Declarative Onboarding Persona Step Definitions
 */

import { UserRole, OnboardingStepDefinition } from '@eurogovernance/shared-types';

export interface PersonaFlowConfig {
  role: UserRole;
  badge: string;
  title: string;
  subtitle: string;
  defaultTab: string;
  steps: OnboardingStepDefinition[];
}

export const PERSONA_ONBOARDING_FLOWS: Record<string, PersonaFlowConfig> = {
  tenant_admin: {
    role: 'tenant_admin',
    badge: 'WORKSPACE ORIENTATION',
    title: 'Organization Setup Orientation',
    subtitle: 'Preview the records and operational modules needed to establish an organization baseline. This walkthrough does not create them.',
    defaultTab: 'overview',
    steps: [
      {
        id: 'admin_org_profile',
        stepIndex: 0,
        title: 'Organization Baseline',
        subtitle: 'Preview legal-entity and jurisdiction inputs; complete the authoritative record in the relevant module.',
        icon: '🏢',
        targetTab: 'overview',
        isMutating: true,
        complianceImpact: 'Identifies inputs for a later legal assessment; Member State selection alone does not determine the GDPR lead authority.',
        recommendedActionLabel: 'Configure Legal Entity',
      },
      {
        id: 'admin_framework_scope',
        stepIndex: 1,
        title: 'Regulatory Framework Scope',
        subtitle: 'Select applicable European directives and certifiable security standards.',
        icon: '📐',
        targetTab: 'frameworks',
        isMutating: true,
        complianceImpact: 'Points to the framework workflow where adoption and scope records can be created.',
        recommendedActionLabel: 'Select Frameworks',
      },
      {
        id: 'admin_scoping_rules',
        stepIndex: 2,
        title: 'Fast-Track Scoping & Harmonization',
        subtitle: 'Answer 4 operational questions to automatically filter non-applicable controls.',
        icon: '⚖️',
        targetTab: 'applicability_review',
        isMutating: true,
        complianceImpact: 'Points to the applicability workspace; no determination is made by onboarding.',
        recommendedActionLabel: 'Run Scoping Engine',
      },
      {
        id: 'admin_appoint_leads',
        stepIndex: 3,
        title: 'Appoint Governance Leads',
        subtitle: 'Delegate specialized statutory domains to internal compliance and security officers.',
        icon: '👥',
        targetTab: 'members',
        isMutating: true,
        complianceImpact: 'Points to membership administration; onboarding itself sends no invitation.',
        recommendedActionLabel: 'Invite Team Leads',
      },
      {
        id: 'admin_governance_policies',
        stepIndex: 4,
        title: 'Evidence Governance & Policies',
        subtitle: 'Enforce sovereign audit rules before operational evidence ingestion begins.',
        icon: '🛡️',
        targetTab: 'controls',
        isMutating: true,
        complianceImpact: 'Explains planned evidence controls; the verified evidence pipeline is not yet available.',
        recommendedActionLabel: 'Enforce Security Policies',
      },
    ],
  },

  compliance_manager: {
    role: 'compliance_manager',
    badge: 'GOVERNANCE ONBOARDING',
    title: 'Multi-Framework Scoping & Harmonization',
    subtitle: 'Navigate to scoping, control, and export records; verify each workflow result before assurance use.',
    defaultTab: 'coverage_dashboard',
    steps: [
      {
        id: 'comp_scoping',
        stepIndex: 0,
        title: 'Operational Scoping Questionnaire',
        subtitle: 'Fine-tune 8 operational parameters to finalize applicable requirements across GDPR & ISO.',
        icon: '📐',
        targetTab: 'applicability_review',
        isMutating: true,
        complianceImpact: 'Determines requirement applicability for the formal Statement of Applicability (SoA).',
        recommendedActionLabel: 'Complete Scoping Questions',
      },
      {
        id: 'comp_exclusions',
        stepIndex: 1,
        title: 'Applicability Determinations',
        subtitle: 'Provide formal statutory justifications for excluded ISO 27001 Annex A controls.',
        icon: '⚖️',
        targetTab: 'applicability_review',
        isMutating: true,
        complianceImpact: 'Mandatory for ISO 27001 certification audit readiness.',
        recommendedActionLabel: 'Document Exclusions',
      },
      {
        id: 'comp_controls_review',
        stepIndex: 2,
        title: 'Unified Controls Inventory Inspection',
        subtitle: 'Inspect mapped control overlaps and verify 100% requirement coverage.',
        icon: '🛡️',
        targetTab: 'controls',
        isMutating: false,
        complianceImpact: 'Supports inspection for unmapped obligations; it does not prove complete coverage.',
        recommendedActionLabel: 'Inspect Controls Catalog',
      },
      {
        id: 'comp_export_dossier',
        stepIndex: 3,
        title: 'Statement of Applicability Pre-flight Scan',
        subtitle: 'Inspect the current server-side structured export draft workflow.',
        icon: '📦',
        targetTab: 'exports',
        isMutating: true,
        complianceImpact: 'Produces a JSON draft when authorized; PDF rendering and browser download are unavailable.',
        recommendedActionLabel: 'Inspect Export Drafts',
      },
    ],
  },

  privacy_manager: {
    role: 'privacy_manager',
    badge: 'STATUTORY PRIVACY',
    title: 'GDPR Article 30 & Transfer Governance',
    subtitle: 'Document processing activities, map cross-border data flows (TIAs), and verify Article 28 DPAs.',
    defaultTab: 'gdpr',
    steps: [
      {
        id: 'dpo_ropa',
        stepIndex: 0,
        title: 'Article 30 Processing Activities Setup',
        subtitle: 'Select pre-built ROPA templates for Customer CRM, HR Payroll, and Cloud Analytics.',
        icon: '🇪🇺',
        targetTab: 'gdpr',
        isMutating: true,
        complianceImpact: 'Supports Article 30 recordkeeping when the ROPA entries are complete, reviewed, and maintained.',
        recommendedActionLabel: 'Initialize ROPA Entries',
      },
      {
        id: 'dpo_transfers',
        stepIndex: 1,
        title: 'Cross-Border Data Flow Mapping (TIAs)',
        subtitle: 'Identify non-EEA cloud processors and attach Standard Contractual Clauses (SCCs).',
        icon: '🌍',
        targetTab: 'processor_transfers',
        isMutating: true,
        complianceImpact: 'Supports documented Chapter V assessment; legal sufficiency still requires review.',
        recommendedActionLabel: 'Map Cross-Border Transfers',
      },
      {
        id: 'dpo_dpa_audit',
        stepIndex: 2,
        title: 'Article 28 DPA Verification',
        subtitle: 'Verify executed Data Processing Agreements for all active suppliers.',
        icon: '📜',
        targetTab: 'processor_hub',
        isMutating: true,
        complianceImpact: 'Helps identify missing or incomplete Article 28 agreements; it does not eliminate legal exposure by itself.',
        recommendedActionLabel: 'Audit DPA Contracts',
      },
    ],
  },

  ai_governance_manager: {
    role: 'ai_governance_manager',
    badge: 'EU AI ACT CONFORMITY',
    title: 'AI Model Register & Risk Classification',
    subtitle: 'Inventory organization AI systems, screen for Article 5 prohibitions, and compile technical dossiers.',
    defaultTab: 'ai_systems',
    steps: [
      {
        id: 'ai_register',
        stepIndex: 0,
        title: 'Register Foundation AI Models',
        subtitle: 'Capture model name, intended purpose, foundation model provider, and deployment context.',
        icon: '🤖',
        targetTab: 'ai_systems',
        isMutating: true,
        complianceImpact: 'Creates an inventory record when the AI-system workflow is completed.',
        recommendedActionLabel: 'Register First AI Model',
      },
      {
        id: 'ai_screening',
        stepIndex: 1,
        title: 'Article 5 Prohibited Practice Screening',
        subtitle: 'Screen for subliminal manipulation, sensitive trait categorization, and social scoring.',
        icon: '🚫',
        targetTab: 'ai_systems',
        isMutating: true,
        complianceImpact: 'Records a screening decision; independent review is still required before relying on it.',
        recommendedActionLabel: 'Run Prohibited Screening',
      },
      {
        id: 'ai_annex_three',
        stepIndex: 2,
        title: 'Annex III High-Risk Classification',
        subtitle: 'Evaluate model impact on employment, critical systems, or credit scoring.',
        icon: '⚖️',
        targetTab: 'ai_systems',
        isMutating: true,
        complianceImpact: 'Records a classification input for review; it does not establish legal conformity on its own.',
        recommendedActionLabel: 'Determine Risk Tier',
      },
    ],
  },

  security_manager: {
    role: 'security_manager',
    badge: 'SECURITY & ASSURANCE',
    title: 'Third-Party Governance & Control Verification',
    subtitle: 'Import critical infrastructure suppliers, dispatch due diligence assessments, and upload ISO 27001 certs.',
    defaultTab: 'processor_hub',
    steps: [
      {
        id: 'sec_import_processors',
        stepIndex: 0,
        title: 'Core Processor Roster Setup',
        subtitle: 'Import critical hosting providers, cloud databases, and SaaS suppliers.',
        icon: '🏢',
        targetTab: 'processor_inventory',
        isMutating: true,
        complianceImpact: 'Supports supplier inventory maintenance when complete and assigned.',
        recommendedActionLabel: 'Import Critical Vendors',
      },
      {
        id: 'sec_dispatch_assessment',
        stepIndex: 1,
        title: 'Dispatch Due Diligence Assessment',
        subtitle: 'Open the hardened assessment-request workflow and issue a controlled access link when configured.',
        icon: '📋',
        targetTab: 'processor_assessments',
        isMutating: true,
        complianceImpact: 'Collects supplier self-declarations for internal review; it does not validate TOMs automatically.',
        recommendedActionLabel: 'Dispatch Questionnaire',
      },
      {
        id: 'sec_cert_vault',
        stepIndex: 2,
        title: 'Upload Master Certifications',
        subtitle: 'Open the certification register; secure artifact upload is not available yet.',
        icon: '🏆',
        targetTab: 'certifications',
        isMutating: true,
        complianceImpact: 'Records certification metadata; artifact verification and complete reminder operations remain pending.',
        recommendedActionLabel: 'Deposit Certificate',
      },
    ],
  },

  auditor: {
    role: 'auditor',
    badge: 'AUDITOR WORKSPACE',
    title: 'Independent Assurance & Evidence Inspection',
    subtitle: 'Inspect authorized records in read-only mode. File inspection, integrity verification, and export download are unavailable.',
    defaultTab: 'overview',
    steps: [
      {
        id: 'audit_soa_inspect',
        stepIndex: 0,
        title: 'Statement of Applicability Review',
        subtitle: 'Inspect mapped requirements and legal justifications for excluded controls.',
        icon: '📐',
        targetTab: 'coverage_dashboard',
        isMutating: false,
        complianceImpact: 'Validates formal certification boundaries and justification sufficiency.',
        recommendedActionLabel: 'Inspect Scoping Matrix',
      },
      {
        id: 'audit_evidence_sample',
        stepIndex: 1,
        title: 'Evidence Record Sampling',
        subtitle: 'Inspect recorded evidence metadata and reviewer attribution.',
        icon: '🔍',
        targetTab: 'evidence',
        isMutating: false,
        complianceImpact: 'Identifies missing evidence, integrity metadata, or reviewer separation.',
        recommendedActionLabel: 'Sample Evidence Records',
      },
      {
        id: 'audit_export_archive',
        stepIndex: 2,
        title: 'Inspect Export Jobs',
        subtitle: 'Review recorded server-side export jobs without creating or downloading artifacts.',
        icon: '📦',
        targetTab: 'exports',
        isMutating: false,
        complianceImpact: 'Shows export job metadata; it does not provide an audit-ready dossier.',
        recommendedActionLabel: 'Inspect Export Jobs',
      },
    ],
  },

  contributor: {
    role: 'contributor',
    badge: 'ACTION REQUIRED',
    title: 'Assigned Remediation & Evidence Inbox',
    subtitle: 'Review compliance records and work items currently available to your account.',
    defaultTab: 'evidence',
    steps: [
      {
        id: 'contrib_queue',
        stepIndex: 0,
        title: 'Review Assigned Controls Queue',
        subtitle: 'Inspect technical controls requiring implementation or evidence artifacts.',
        icon: '📋',
        targetTab: 'evidence',
        isMutating: false,
        complianceImpact: 'Aligns day-to-day engineering tasks with regulatory requirements.',
        recommendedActionLabel: 'View Assigned Controls',
      },
      {
        id: 'contrib_upload',
        stepIndex: 1,
        title: 'Evidence Upload Pipeline Status',
        subtitle: 'Inspect the evidence workspace; secure upload and server-side SHA-256 verification are unavailable.',
        icon: '📤',
        targetTab: 'evidence',
        isMutating: false,
        complianceImpact: 'Explains the current limitation without creating phantom evidence metadata.',
        recommendedActionLabel: 'Inspect Evidence Workspace',
      },
    ],
  },

  approver: {
    role: 'approver',
    badge: 'APPROVAL WORKSPACE',
    title: 'Independent Governance Review',
    subtitle: 'Review submitted records and verify that decisions are supported by sufficient evidence.',
    defaultTab: 'evidence',
    steps: [
      {
        id: 'approver_evidence_queue',
        stepIndex: 0,
        title: 'Inspect Evidence Review Queue',
        subtitle: 'Review the evidence metadata currently awaiting an authorized decision.',
        icon: '🔍',
        targetTab: 'evidence',
        isMutating: false,
        complianceImpact: 'Supports independent review without granting control over submitted content.',
        recommendedActionLabel: 'Inspect Review Queue',
      },
    ],
  },

  viewer: {
    role: 'viewer',
    badge: 'READ-ONLY ACCESS',
    title: 'Governance Visibility',
    subtitle: 'Inspect authorized governance records without changing organization state.',
    defaultTab: 'overview',
    steps: [
      {
        id: 'viewer_workspace_orientation',
        stepIndex: 0,
        title: 'Review Available Governance Records',
        subtitle: 'Navigate the records and reports made available to your read-only role.',
        icon: '👁️',
        targetTab: 'overview',
        isMutating: false,
        complianceImpact: 'Provides visibility without granting operational or approval permissions.',
        recommendedActionLabel: 'Open Overview',
      },
    ],
  },
};
